import React from 'react';
import TableLayout from './TableLayout';


const ListOfSalesInvoice = () => {
  const initialData = [
    {
      selected: false,
      audited: false,
      date: '01/04/2025',
      cashDebit: 'Cash',
      no: 'INV001',
      taxType: 'GST',
      accountName: 'ABC Corp',
      invtype: 'Standard',
      salesAccount: 'Sales - General',
      totalAmount: 15000.00,
      createdBy: 'John Doe',
      totalArticle: 10,
      totalWeight: 500,
      taxableAmount: 1100,
      itemFreight: 1155,
      expenseName: 'Service Charge',
      expenseAccount: 'Expense - Service',
      expenseRate: 100,
      expenseAmount: 100,
    },
    {
      selected: false,
      audited: false,
      date: '02/04/2025',
      cashDebit: 'Debit',
      no: 'INV002',
      taxType: 'VAT',
      accountName: 'XYZ Ltd',
      invtype: 'Proforma',
      salesAccount: 'Sales - Retail',
      totalAmount: 25000.00,
      createdBy: 'Jane Smith',
      totalArticle: 15,
      totalWeight: 750,
      taxableAmount: 1205,
      itemFreight: 1265.25,
      expenseName: 'Insurance',
      expenseAccount: 'Expense - Insurance',
      expenseRate: 50,
      expenseAmount: 50,
    },
    {
      selected: false,
      audited: false,
      date: '03/04/2025',
      cashDebit: 'Credit',
      no: 'INV003',
      taxType: 'GST',
      accountName: 'DEF Inc',
      invtype: 'Standard',
      salesAccount: 'Sales - Wholesale',
      totalAmount: 18000.50,
      createdBy: 'Mike Johnson',
      totalArticle: 20,
      totalWeight: 1000,
      taxableAmount: 1920,
      itemFreight: 2016,
      expenseName: 'Packaging Fee',
      expenseAccount: 'Expense - General',
      expenseRate: 75,
      expenseAmount: 75,
    },
    {
      selected: false,
      audited: false,
      date: '04/04/2025',
      cashDebit: 'Cash',
      no: 'INV004',
      taxType: 'VAT',
      accountName: 'GHI LLC',
      invtype: 'Proforma',
      salesAccount: 'Sales - Services',
      totalAmount: 32000.75,
      createdBy: 'Sarah Williams',
      totalArticle: 12,
      totalWeight: 600,
      taxableAmount: 1300,
      itemFreight: 1365,
      expenseName: 'Other',
      expenseAccount: 'Expense - General',
      expenseRate: 200,
      expenseAmount: 200,
    },
    {
      selected: false,
      audited: false,
      date: '05/04/2025',
      cashDebit: 'Debit',
      no: 'INV005',
      taxType: 'GST',
      accountName: 'JKL Enterprises',
      invtype: 'Standard',
      salesAccount: 'Sales - General',
      totalAmount: 12500.00,
      createdBy: 'David Brown',
      totalArticle: 8,
      totalWeight: 400,
      taxableAmount: 900,
      itemFreight: 945,
      expenseName: 'Service Charge',
      expenseAccount: 'Expense - Service',
      expenseRate: 150,
      expenseAmount: 150,
    },
    {
      selected: false,
      audited: false,
      date: '06/04/2025',
      cashDebit: 'Credit',
      no: 'INV006',
      taxType: 'VAT',
      accountName: 'MNO Group',
      invtype: 'Standard',
      salesAccount: 'Sales - Retail',
      totalAmount: 27500.25,
      createdBy: 'Emily Davis',
      totalArticle: 18,
      totalWeight: 900,
      taxableAmount: 1600,
      itemFreight: 1680,
      expenseName: 'Insurance',
      expenseAccount: 'Expense - Insurance',
      expenseRate: 120,
      expenseAmount: 120,
    },
    {
      selected: false,
      audited: false,
      date: '07/04/2025',
      cashDebit: 'Cash',
      no: 'INV007',
      taxType: 'GST',
      accountName: 'PQR Solutions',
      invtype: 'Proforma',
      salesAccount: 'Sales - Wholesale',
      totalAmount: 22000.00,
      createdBy: 'Robert Wilson',
      totalArticle: 14,
      totalWeight: 700,
      taxableAmount: 1400,
      itemFreight: 1470,
      expenseName: 'Packaging Fee',
      expenseAccount: 'Expense - General',
      expenseRate: 90,
      expenseAmount: 90,
    },
    {
      selected: false,
      audited: false,
      date: '08/04/2025',
      cashDebit: 'Debit',
      no: 'INV008',
      taxType: 'VAT',
      accountName: 'STU Technologies',
      invtype: 'Standard',
      salesAccount: 'Sales - Services',
      totalAmount: 19500.50,
      createdBy: 'Lisa Taylor',
      totalArticle: 16,
      totalWeight: 800,
      taxableAmount: 1500,
      itemFreight: 1575,
      expenseName: 'Other',
      expenseAccount: 'Expense - General',
      expenseRate: 180,
      expenseAmount: 180,
    },
    {
      selected: false,
      audited: false,
      date: '09/04/2025',
      cashDebit: 'Credit',
      no: 'INV009',
      taxType: 'GST',
      accountName: 'VWX Industries',
      invtype: 'Proforma',
      salesAccount: 'Sales - General',
      totalAmount: 28500.75,
      createdBy: 'James Anderson',
      totalArticle: 22,
      totalWeight: 1100,
      taxableAmount: 2000,
      itemFreight: 2100,
      expenseName: 'Service Charge',
      expenseAccount: 'Expense - Service',
      expenseRate: 110,
      expenseAmount: 110,
    },
    {
      selected: false,
      audited: false,
      date: '10/04/2025',
      cashDebit: 'Cash',
      no: 'INV010',
      taxType: 'VAT',
      accountName: 'YZ Systems',
      invtype: 'Standard',
      salesAccount: 'Sales - Retail',
      totalAmount: 16500.00,
      createdBy: 'Jennifer Martinez',
      totalArticle: 9,
      totalWeight: 450,
      taxableAmount: 1000,
      itemFreight: 1050,
      expenseName: 'Insurance',
      expenseAccount: 'Expense - Insurance',
      expenseRate: 130,
      expenseAmount: 130,
    },
  ];

  const columns = [
    { label: 'A', field: 'selected' },
    { label: 'Audited', field: 'audited' },
    { label: 'Date', field: 'date' },
    { label: 'Cash/Debit', field: 'cashDebit' },
    { label: 'No', field: 'no' },
    { label: 'Tax Type', field: 'taxType' },
    { label: 'Account Name', field: 'accountName' },
    { label: 'Invtype', field: 'invtype' },
    { label: 'Sales Account', field: 'salesAccount' },
    { label: 'Total Amount', field: 'totalAmount' },
    { label: 'Created By', field: 'createdBy' },
  ];

  const numericFields = [
    'totalAmount',
    'article',
    'weight',
    'rate',
    'lrFreight',
    'bc',
    'hamali',
    'otherCharge',
    'subTotal',
    'gst',
    'totalFreight',
    'totalArticle',
    'totalWeight',
    'amount',
    'balance',
    'taxableAmount',
    'itemFreight',
    'expenseRate',
    'expenseAmount',
  ];

  const fieldConfig = {
    cashDebit: { options: ['Cash', 'Debit', 'Credit'] },
    taxType: { options: ['GST', 'VAT', 'TAX FREE'] },
    invtype: { options: ['Standard', 'Proforma'] },
    salesAccount: {
      options: ['Sales - General', 'Sales - Retail', 'Sales - Wholesale', 'Sales - Services'],
    },
    fromBranch: {
      options: [
        'MUMBAI',
        'AHMEDABAD',
        'DELHI',
        'PUNE',
        'BANGALORE',
        'HYDERABAD',
        'KOLKATA',
        'CHENNAI',
        'SURAT',
        'NAGPUR',
      ],
    },
    expenseName: {
      options: ['Service Charge', 'Packaging Fee', 'Insurance', 'Other'],
    },
    expenseAccount: {
      options: ['Expense - General', 'Expense - Service', 'Expense - Insurance'],
    },
  };

  const windowConfig = {
    initialState: {
      selected: false,
      audited: false,
      date: new Date().toLocaleDateString('en-GB').split('/').join('/'),
      cashDebit: 'Debit',
      no: '',
      taxType: 'GST',
      accountName: '',
      invtype: 'Standard',
      salesAccount: 'Sales - General',
      totalAmount: 0,
      createdBy: '',
      billType: 'Lr',
      bookCode: '',
      balance: 0,
      centerName: '',
      lrNo: '',
      lrDate: '',
      delDate: '',
      consigner: '',
      consignee: '',
      truckNo: '',
      fromCity: '',
      toCity: '',
      fromBranch: '',
      hsnSac: '',
      article: 0,
      weight: 0,
      taxableAmount: 0,
      itemFreight: 0,
      narration: '',
      expenseName: '',
      expenseAccount: '',
      expenseRate: 0,
      expenseAmount: 0,
      rate: 0,
      amount: 0,
      totalArticle: 0,
      totalWeight: 0,
      lrFreight: 0,
      bc: 0,
      hamali: 0,
      otherCharge: 0,
      subTotal: 0,
      gst: 0,
      totalFreight: 0,
      rows: [],
    },
    fieldMapping: (entry) => ({
      selected: entry.selected || false,
      audited: entry.audited || false,
      date: entry.date || '',
      cashDebit: entry.cashDebit || '',
      no: entry.no || '',
      taxType: entry.taxType || '',
      accountName: entry.accountName || '',
      invtype: entry.invtype || '',
      salesAccount: entry.salesAccount || '',
      totalAmount: parseFloat(entry.totalAmount) || 0,
      createdBy: entry.createdBy || '',
      billType: entry.billType || '',
      bookCode: entry.bookCode || '',
      balance: parseFloat(entry.balance) || 0,
      centerName: entry.centerName || '',
      lrNo: entry.lrNo || '',
      lrDate: entry.lrDate || '',
      delDate: entry.delDate || '',
      consigner: entry.consigner || '',
      consignee: entry.consignee || '',
      truckNo: entry.truckNo || '',
      fromCity: entry.fromCity || '',
      toCity: entry.toCity || '',
      fromBranch: entry.fromBranch || '',
      hsnSac: entry.hsnSac || '',
      article: parseInt(entry.article) || 0,
      weight: parseFloat(entry.weight) || 0,
      taxableAmount: parseFloat(entry.taxableAmount) || 0,
      itemFreight: parseFloat(entry.itemFreight) || 0,
      narration: entry.narration || '',
      expenseName: entry.expenseName || '',
      expenseAccount: entry.expenseAccount || '',
      expenseRate: parseFloat(entry.expenseRate) || 0,
      expenseAmount: parseFloat(entry.expenseAmount) || 0,
      rate: parseFloat(entry.rate) || 0,
      amount: parseFloat(entry.amount) || 0,
      totalArticle: parseInt(entry.totalArticle) || 0,
      totalWeight: parseFloat(entry.totalWeight) || 0,
      lrFreight: parseFloat(entry.lrFreight) || 0,
      bc: parseFloat(entry.bc) || 0,
      hamali: parseFloat(entry.hamali) || 0,
      otherCharge: parseFloat(entry.otherCharge) || 0,
      subTotal: parseFloat(entry.subTotal) || 0,
      gst: parseFloat(entry.gst) || 0,
      totalFreight: parseFloat(entry.totalFreight) || 0,
      rows: entry.rows || [],
    }),
  };

  return (
    <TableLayout
      title="List of Sales Invoice"
      columns={columns}
      initialData={initialData}
      numericFields={numericFields}
      fieldConfig={fieldConfig}
      windowConfig={windowConfig}
      componentType="salesInvoice"
      showAdd={true}
      showEdit={true}
      showView={true}
      showDelete={true}
      showRefresh={true}
      showPrint={true}
      showAudit={true}
      showField={true}
      showExportExcel={true}
      showExportPDF={true}
   
    />
  );
};

export default ListOfSalesInvoice;