import React from 'react';
import TableLayout from './TableLayout';

const ListOfMemoReceived = () => {
  const initialData = [
    {
      selected: false,
      audited: false,
      date: '01/04/2025',
      receiveNo: '1',
      memo: 'Memo 1',
      center: 'HEAD OFFICE',
      lrNo: 'LR001',
      lrDate: '01/04/2025',
      baleNo: 'B001',
      fromCity: 'MUMBAI',
      city: 'AHMEDABAD',
      consignor: 'ABC Corp',
      consignee: 'XYZ Ltd',
      article: 5,
      shortArt: 0,
      weight: 100.00,
      freight: 1500.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '02/04/2025',
      receiveNo: '2',
      memo: 'Memo 2',
      center: 'MUMBAI BRANCH',
      lrNo: 'LR002',
      lrDate: '02/04/2025',
      baleNo: 'B002',
      fromCity: 'DELHI',
      city: 'PUNE',
      consignor: 'DEF Inc',
      consignee: 'PQR Ltd',
      article: 3,
      shortArt: 0,
      weight: 50.00,
      freight: 800.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '03/04/2025',
      receiveNo: '3',
      memo: 'Memo 3',
      center: 'DELHI BRANCH',
      lrNo: 'LR003',
      lrDate: '03/04/2025',
      baleNo: 'B003',
      fromCity: 'PUNE',
      city: 'JAIPUR',
      consignor: 'GHI Ltd',
      consignee: 'STU Corp',
      article: 7,
      shortArt: 0,
      weight: 120.00,
      freight: 1800.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '04/04/2025',
      receiveNo: '4',
      memo: 'Memo 4',
      center: 'HEAD OFFICE',
      lrNo: 'LR004',
      lrDate: '04/04/2025',
      baleNo: 'B004',
      fromCity: 'BANGALORE',
      city: 'KOTA',
      consignor: 'JKL Inc',
      consignee: 'VWX Ltd',
      article: 4,
      shortArt: 0,
      weight: 80.00,
      freight: 1200.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '05/04/2025',
      receiveNo: '5',
      memo: 'Memo 5',
      center: 'MUMBAI BRANCH',
      lrNo: 'LR005',
      lrDate: '05/04/2025',
      baleNo: 'B005',
      fromCity: 'MUMBAI',
      city: 'SURAT',
      consignor: 'MNO Corp',
      consignee: 'YZA Ltd',
      article: 6,
      shortArt: 0,
      weight: 90.00,
      freight: 1350.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '06/04/2025',
      receiveNo: '6',
      memo: 'Memo 6',
      center: 'DELHI BRANCH',
      lrNo: 'LR006',
      lrDate: '06/04/2025',
      baleNo: 'B006',
      fromCity: 'DELHI',
      city: 'AHMEDABAD',
      consignor: 'PQR Inc',
      consignee: 'BCD Ltd',
      article: 8,
      shortArt: 0,
      weight: 110.00,
      freight: 1650.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '07/04/2025',
      receiveNo: '7',
      memo: 'Memo 7',
      center: 'HEAD OFFICE',
      lrNo: 'LR007',
      lrDate: '07/04/2025',
      baleNo: 'B007',
      fromCity: 'PUNE',
      city: 'PUNE',
      consignor: 'STU Corp',
      consignee: 'EFG Ltd',
      article: 2,
      shortArt: 0,
      weight: 40.00,
      freight: 600.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '08/04/2025',
      receiveNo: '8',
      memo: 'Memo 8',
      center: 'MUMBAI BRANCH',
      lrNo: 'LR008',
      lrDate: '08/04/2025',
      baleNo: 'B008',
      fromCity: 'BANGALORE',
      city: 'JAIPUR',
      consignor: 'VWX Inc',
      consignee: 'HIJ Ltd',
      article: 9,
      shortArt: 0,
      weight: 130.00,
      freight: 1950.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '09/04/2025',
      receiveNo: '9',
      memo: 'Memo 9',
      center: 'DELHI BRANCH',
      lrNo: 'LR009',
      lrDate: '09/04/2025',
      baleNo: 'B009',
      fromCity: 'MUMBAI',
      city: 'KOTA',
      consignor: 'YZA Corp',
      consignee: 'KLM Ltd',
      article: 5,
      shortArt: 0,
      weight: 70.00,
      freight: 1050.00,
      freightBy: 'TBB',
    },
    {
      selected: false,
      audited: false,
      date: '10/04/2025',
      receiveNo: '10',
      memo: 'Memo 10',
      center: 'HEAD OFFICE',
      lrNo: 'LR010',
      lrDate: '10/04/2025',
      baleNo: 'B010',
      fromCity: 'DELHI',
      city: 'SURAT',
      consignor: 'BCD Inc',
      consignee: 'NOP Ltd',
      article: 6,
      shortArt: 0,
      weight: 85.00,
      freight: 1275.00,
      freightBy: 'TBB',
    },
  ];

  const columns = [
    { label: 'A', field: 'selected' },
    { label: 'Audited', field: 'audited' },
    { label: 'Date', field: 'date' },
    { label: 'Receive No', field: 'receiveNo' },
    { label: 'Memo', field: 'memo' },
    { label: 'Center', field: 'center' },
    { label: 'Lr No', field: 'lrNo' },
    { label: 'Lr Date', field: 'lrDate' },
    { label: 'Bale No', field: 'baleNo' },
    { label: 'From City', field: 'fromCity' },
    { label: 'City', field: 'city' },
    { label: 'Consignor', field: 'consignor' },
    { label: 'Consignee', field: 'consignee' },
    { label: 'Article', field: 'article' },
    { label: 'Short Art', field: 'shortArt' },
    { label: 'Weight', field: 'weight' },
    { label: 'Freight', field: 'freight' },
    { label: 'Freight By', field: 'freightBy' },
  ];

  const numericFields = ['article', 'shortArt', 'weight', 'freight'];

  const fieldConfig = {
    center: { options: ['HEAD OFFICE', 'MUMBAI BRANCH', 'DELHI BRANCH'] },
    fromCity: { options: ['MUMBAI', 'DELHI', 'PUNE', 'BANGALORE'] },
    toCity: { options: ['AHMEDABAD', 'KOTA', 'JAIPUR', 'SURAT', 'PUNE'] },
    freightBy: { options: ['TBB', 'To Pay', 'Paid', 'Consignee', 'Consignor'] },
  };

  const windowConfig = {
    initialState: {
      selected: false,
      audited: false,
      date: new Date().toLocaleDateString('en-GB').split('/').join('/'),
      receiveNo: '',
      memo: '',
      center: '',
      lrNo: '',
      lrDate: '',
      baleNo: '',
      fromCity: '',
      city: '',
      consignor: '',
      consignee: '',
      article: 0,
      shortArt: 0,
      weight: 0,
      freight: 0,
      freightBy: '',
      balance: 0,
      totalFreight: 0,
      narration: '',
      lrRows: [
        {
          centerName: '',
          lrNo: '',
          date: '',
          baleNo: '',
          fromCity: '',
          toCity: '',
          consignor: '',
          consignee: '',
          article: 0,
          shortArt: 0,
          weight: 0,
          freight: 0,
          freightBy: '',
        },
      ],
    },
    fieldMapping: (entry) => {
      const firstLrRow = entry.lrRows && entry.lrRows.length > 0 ? entry.lrRows[0] : {};
      return {
        selected: entry.selected || false,
        audited: entry.audited || false,
        date: entry.date || '',
        receiveNo: entry.memoNo || entry.receiveNo || '',
        memo: entry.memo || '',
        center: firstLrRow.centerName || entry.center || '',
        lrNo: firstLrRow.lrNo || entry.lrNo || '',
        lrDate: firstLrRow.date || entry.lrDate || '',
        baleNo: firstLrRow.baleNo || entry.baleNo || '',
        fromCity: firstLrRow.fromCity || entry.fromCity || '',
        city: firstLrRow.toCity || entry.city || '',
        consignor: firstLrRow.consignor || entry.consignor || '',
        consignee: firstLrRow.consignee || entry.consignee || '',
        article: parseInt(firstLrRow.article) || parseInt(entry.article) || 0,
        shortArt: parseInt(firstLrRow.shortArt) || parseInt(entry.shortArt) || 0,
        weight: parseFloat(firstLrRow.weight) || parseFloat(entry.weight) || 0,
        freight: parseFloat(firstLrRow.freight) || parseFloat(entry.freight) || parseFloat(entry.totalFreight) || 0,
        freightBy: firstLrRow.freightBy || entry.freightBy || '',
        balance: parseFloat(entry.balance) || 0,
        totalFreight: parseFloat(entry.totalFreight) || 0,
        narration: entry.narration || '',
        lrRows: entry.lrRows || [],
      };
    },
  };

  return (
    <TableLayout
      title="List of Memo Receive"
      columns={columns}
      initialData={initialData}
      numericFields={numericFields}
      fieldConfig={fieldConfig}
      windowConfig={windowConfig}
      componentType="memoreceive"
      showAdd={true}
      showEdit={true}
      showView={true}
      showDelete={true}
      showRefresh={true}
      showPrint={true}
      showAudit={true}
      showField={true}
      showExportExcel={true}
      showExportPDF={true}
    />
  );
};

export default ListOfMemoReceived;