import React from 'react';
import TableLayout from './TableLayout';

const ListOfMemo = () => {
  const initialData = [
    {
      selected: false,
      audited: true,
      date: '28/04/2025',
      memoNo: '7',
      toBranch: 'To Branch 1',
      vehicle: 'Vehicle 1',
      driver: 'Driver 1',
      agent: 'Agent 1',
      hire: 'Hire 1',
      cashBank: 'Cash',
      center: 'Center 1',
      packaging: 'Bag',
      description: 'Sample 1',
      article: 10,
      freightBy: 'TBB',
      fromCity: 'MUMBAI',
      toPay: 100.00,
      paid: 50.00,
      narration: 'Test Memo 1',
      memoFreight: 150.00,
    },
    {
      selected: false,
      audited: false,
      date: '29/04/2025',
      memoNo: '8',
      toBranch: 'To Branch 2',
      vehicle: 'Vehicle 2',
      driver: 'Driver 2',
      agent: 'Agent 2',
      hire: 'Hire 2',
      cashBank: 'Bank',
      center: 'Center 2',
      packaging: 'Box',
      description: 'Sample 2',
      article: 5,
      freightBy: 'TBB',
      fromCity: 'DELHI',
      toPay: 200.00,
      paid: 100.00,
      narration: 'Test Memo 2',
      memoFreight: 300.00,
    },
    {
      selected: false,
      audited: true,
      date: '30/04/2025',
      memoNo: '9',
      toBranch: 'To Branch 3',
      vehicle: 'Vehicle 3',
      driver: 'Driver 3',
      agent: 'Agent 3',
      hire: 'Hire 3',
      cashBank: 'Cash',
      center: 'Center 3',
      packaging: 'Carton',
      description: 'Sample 3',
      article: 8,
      freightBy: 'TBB',
      fromCity: 'PUNE',
      toPay: 150.00,
      paid: 75.00,
      narration: 'Test Memo 3',
      memoFreight: 225.00,
    },
    {
      selected: false,
      audited: false,
      date: '01/05/2025',
      memoNo: '10',
      toBranch: 'To Branch 4',
      vehicle: 'Vehicle 4',
      driver: 'Driver 4',
      agent: 'Agent 4',
      hire: 'Hire 4',
      cashBank: 'Bank',
      center: 'Center 4',
      packaging: 'Bag',
      description: 'Sample 4',
      article: 12,
      freightBy: 'TBB',
      fromCity: 'BANGALORE',
      toPay: 300.00,
      paid: 150.00,
      narration: 'Test Memo 4',
      memoFreight: 450.00,
    },
    {
      selected: false,
      audited: false,
      date: '02/05/2025',
      memoNo: '11',
      toBranch: 'To Branch 5',
      vehicle: 'Vehicle 5',
      driver: 'Driver 5',
      agent: 'Agent 5',
      hire: 'Hire 5',
      cashBank: 'Cash',
      center: 'Center 5',
      packaging: 'Box',
      description: 'Sample 5',
      article: 15,
      freightBy: 'TBB',
      fromCity: 'MUMBAI',
      toPay: 250.00,
      paid: '125.00',
      narration: 'Test Memo 5',
      memoFreight: 375.00,
    },
    {
      selected: false,
      audited: true,
      date: '03/05/2025',
      memoNo: '12',
      toBranch: 'To Branch 6',
      vehicle: 'Vehicle 6',
      driver: 'Driver 6',
      agent: 'Agent 6',
      hire: 'Hire 6',
      cashBank: 'Bank',
      center: 'Center 6',
      packaging: 'Carton',
      description: 'Sample 6',
      article: 7,
      freightBy: 'TBB',
      fromCity: 'DELHI',
      toPay: 180.00,
      paid: 90.00,
      narration: 'Test Memo 6',
      memoFreight: 270.00,
    },
    {
      selected: false,
      audited: false,
      date: '04/05/2025',
      memoNo: '13',
      toBranch: 'To Branch 7',
      vehicle: 'Vehicle 7',
      driver: 'Driver 7',
      agent: 'Agent 7',
      hire: 'Hire 7',
      cashBank: 'Cash',
      center: 'Center 7',
      packaging: 'Bag',
      description: 'Sample 7',
      article: 9,
      freightBy: 'TBB',
      fromCity: 'PUNE',
      toPay: 220.00,
      paid: 110.00,
      narration: 'Test Memo 7',
      memoFreight: 330.00,
    },
    {
      selected: false,
      audited: false,
      date: '05/05/2025',
      memoNo: '14',
      toBranch: 'To Branch 8',
      vehicle: 'Vehicle 8',
      driver: 'Driver 8',
      agent: 'Agent 8',
      hire: 'Hire 8',
      cashBank: 'Bank',
      center: 'Center 8',
      packaging: 'Box',
      description: 'Sample 8',
      article: 11,
      freightBy: 'TBB',
      fromCity: 'BANGALORE',
      toPay: 280.00,
      paid: 140.00,
      narration: 'Test Memo 8',
      memoFreight: 420.00,
    },
    {
      selected: false,
      audited: true,
      date: '06/05/2025',
      memoNo: '15',
      toBranch: 'To Branch 9',
      vehicle: 'Vehicle 9',
      driver: 'Driver 9',
      agent: 'Agent 9',
      hire: 'Hire 9',
      cashBank: 'Cash',
      center: 'Center 9',
      packaging: 'Carton',
      description: 'Sample 9',
      article: 6,
      freightBy: 'TBB',
      fromCity: 'MUMBAI',
      toPay: 190.00,
      paid: 95.00,
      narration: 'Test Memo 9',
      memoFreight: 285.00,
    },
    {
      selected: false,
      audited: false,
      date: '07/05/2025',
      memoNo: '16',
      toBranch: 'To Branch 10',
      vehicle: 'Vehicle 10',
      driver: 'Driver 10',
      agent: 'Agent 10',
      hire: 'Hire 10',
      cashBank: 'Bank',
      center: 'Center 10',
      packaging: 'Bag',
      description: 'Sample 10',
      article: 14,
      freightBy: 'TBB',
      fromCity: 'DELHI',
      toPay: 260.00,
      paid: 130.00,
      narration: 'Test Memo 10',
      memoFreight: 390.00,
    },
  ];

  const columns = [
    { label: 'A', field: 'selected' },
    { label: 'Audited', field: 'audited' },
    { label: 'Date', field: 'date' },
    { label: 'Memo No', field: 'memoNo' },
    { label: 'To Branch', field: 'toBranch' },
    { label: 'Vehicle', field: 'vehicle' },
    { label: 'Driver', field: 'driver' },
    { label: 'Agent', field: 'agent' },
    { label: 'Hire', field: 'hire' },
    { label: 'Cash/Bank', field: 'cashBank' },
    { label: 'Center', field: 'center' },
    { label: 'Packaging', field: 'packaging' },
    { label: 'Description', field: 'description' },
    { label: 'Article', field: 'article' },
    { label: 'Freight By', field: 'freightBy' },
    { label: 'From City', field: 'fromCity' },
    { label: 'To Pay', field: 'toPay' },
    { label: 'Paid', field: 'paid' },
    { label: 'Narration', field: 'narration' },
    { label: 'Memo Freight', field: 'memoFreight' },
  ];

  const numericFields = ['article', 'toPay', 'paid', 'memoFreight'];

  const fieldConfig = {
    toBranch: {
      options: [
        'To Branch 1',
        'To Branch 2',
        'To Branch 3',
        'To Branch 4',
        'To Branch 5',
        'To Branch 6',
        'To Branch 7',
        'To Branch 8',
        'To Branch 9',
        'To Branch 10',
      ],
    },
    vehicle: {
      options: [
        'Vehicle 1',
        'Vehicle 2',
        'Vehicle 3',
        'Vehicle 4',
        'Vehicle 5',
        'Vehicle 6',
        'Vehicle 7',
        'Vehicle 8',
        'Vehicle 9',
        'Vehicle 10',
      ],
    },
    driver: {
      options: [
        'Driver 1',
        'Driver 2',
        'Driver 3',
        'Driver 4',
        'Driver 5',
        'Driver 6',
        'Driver 7',
        'Driver 8',
        'Driver 9',
        'Driver 10',
      ],
    },
    agent: {
      options: [
        'Agent 1',
        'Agent 2',
        'Agent 3',
        'Agent 4',
        'Agent 5',
        'Agent 6',
        'Agent 7',
        'Agent 8',
        'Agent 9',
        'Agent 10',
      ],
    },
    hire: {
      options: [
        'Hire 1',
        'Hire 2',
        'Hire 3',
        'Hire 4',
        'Hire 5',
        'Hire 6',
        'Hire 7',
        'Hire 8',
        'Hire 9',
        'Hire 10',
      ],
    },
    cashBank: {
      options: ['Cash', 'Bank'],
    },
    center: {
      options: [
        'Center 1',
        'Center 2',
        'Center 3',
        'Center 4',
        'Center 5',
        'Center 6',
        'Center 7',
        'Center 8',
        'Center 9',
        'Center 10',
      ],
    },
    packaging: {
      options: ['Bag', 'Box', 'Carton'],
    },
    freightBy: {
      options: ['TBB'],
    },
    fromCity: {
      options: ['MUMBAI', 'DELHI', 'PUNE', 'BANGALORE'],
    },
  };

  const windowConfig = {
    initialState: {
      date: '',
      memoNo: '',
      toBranch: '',
      vehicle: '',
      driver: '',
      agent: '',
      hire: '',
      cashBank: '',
      center: '',
      packaging: '',
      description: '',
      article: 0,
      freightBy: '',
      fromCity: '',
      toPay: 0,
      paid: 0,
      narration: '',
      memoFreight: 0,
      kMiter: '',
      addLr: false,
      autoAddLr: false,
      totalLr: 0,
      totalArticle: 0,
      totalAcWeight: 0,
      totalWeight: 0,
      freightByArticle: 0,
    },
    fieldMapping: (entry) => ({
      date: entry.date,
      memoNo: entry.memoNo,
      toBranch: entry.toBranch,
      vehicle: entry.vehicle,
      driver: entry.driver,
      agent: entry.agent,
      hire: entry.hire,
      cashBank: entry.cashBank,
      center: entry.center,
      packaging: entry.packaging,
      description: entry.description,
      article: parseInt(entry.article) || 0,
      freightBy: entry.freightBy,
      fromCity: entry.fromCity,
      toPay: parseFloat(entry.toPay) || 0,
      paid: parseFloat(entry.paid) || 0,
      narration: entry.narration,
      memoFreight: parseFloat(entry.memoFreight) || 0,
    }),
  };

  return (
    
      <TableLayout
        title="List of Memo"
        columns={columns}
        initialData={initialData}
        numericFields={numericFields}
        fieldConfig={fieldConfig}
        windowConfig={windowConfig}
        componentType="memo"
        showAdd={true}
        showEdit={true}
        showView={true}
        showDelete={true}
        showRefresh={true}
        showPrint={true}
        showAudit={true}
        showField={true}
        showExportExcel={true}
        showExportPDF={true}
      />
  );
};

export default ListOfMemo;