import React from 'react';
import TableLayout from './TableLayout';

const ListOfMemo = () => {
  const initialData = [
    {
      selected: false,
      audited: true,
      date: '28/04/2025',
      memoNo: '7',
      toBranch: 'To Branch 1',
      vehicle: 'Vehicle 1',
      driver: 'Driver 1',
      agent: 'Agent 1',
      hire: 'Hire 1',
      cashBank: 'Cash',
      center: 'Center 1',
      packaging: 'Bag',
      description: 'Sample 1',
      article: 10,
      freightBy: 'TBB',
      fromCity: 'MUMBAI',
      toPay: 100.00,
      paid: 50.00,
      narration: 'Test Memo 1',
      memoFreight: 150.00,
      lrRows: [
        {
          centerName: 'Center 1',
          lrNo: '1001',
          date: '28/04/2025',
          packaging: 'Bag',
          description: 'Sample 1',
          article: 5,
          freightBy: 'TBB',
          fromCity: 'MUMBAI',
          toCity: 'DELHI',
          consignee: 'Consignee 1',
          acWeight: 100,
          weight: 100,
          freight: 75,
        },
        {
          centerName: 'Center 1',
          lrNo: '1002',
          date: '28/04/2025',
          packaging: 'Bag',
          description: 'Sample 1',
          article: 5,
          freightBy: 'TBB',
          fromCity: 'MUMBAI',
          toCity: 'DELHI',
          consignee: 'Consignee 2',
          acWeight: 100,
          weight: 100,
          freight: 75,
        },
      ],
      totalArticle: 10,
      totalAcWeight: 200,
      totalWeight: 200,
      totalFreight: 150,
    },
    {
      selected: false,
      audited: false,
      date: '29/04/2025',
      memoNo: '8',
      toBranch: 'To Branch 2',
      vehicle: 'Vehicle 2',
      driver: 'Driver 2',
      agent: 'Agent 2',
      hire: 'Hire 2',
      cashBank: 'Bank',
      center: 'Center 2',
      packaging: 'Box',
      description: 'Sample 2',
      article: 5,
      freightBy: 'TBB',
      fromCity: 'DELHI',
      toPay: 200.00,
      paid: 100.00,
      narration: 'Test Memo 2',
      memoFreight: 300.00,
      lrRows: [
        {
          centerName: 'Center 2',
          lrNo: '1003',
          date: '29/04/2025',
          packaging: 'Box',
          description: 'Sample 2',
          article: 5,
          freightBy: 'TBB',
          fromCity: 'DELHI',
          toCity: 'PUNE',
          consignee: 'Consignee 3',
          acWeight: 150,
          weight: 150,
          freight: 300,
        },
      ],
      totalArticle: 5,
      totalAcWeight: 150,
      totalWeight: 150,
      totalFreight: 300,
    },
    {
      selected: false,
      audited: true,
      date: '30/04/2025',
      memoNo: '9',
      toBranch: 'To Branch 3',
      vehicle: 'Vehicle 3',
      driver: 'Driver 3',
      agent: 'Agent 3',
      hire: 'Hire 3',
      cashBank: 'Cash',
      center: 'Center 3',
      packaging: 'Carton',
      description: 'Sample 3',
      article: 8,
      freightBy: 'TBB',
      fromCity: 'PUNE',
      toPay: 150.00,
      paid: 75.00,
      narration: 'Test Memo 3',
      memoFreight: 225.00,
      lrRows: [
        {
          centerName: 'Center 3',
          lrNo: '1004',
          date: '30/04/2025',
          packaging: 'Carton',
          description: 'Sample 3',
          article: 8,
          freightBy: 'TBB',
          fromCity: 'PUNE',
          toCity: 'BANGALORE',
          consignee: 'Consignee 4',
          acWeight: 120,
          weight: 120,
          freight: 225,
        },
      ],
      totalArticle: 8,
      totalAcWeight: 120,
      totalWeight: 120,
      totalFreight: 225,
    },
    {
      selected: false,
      audited: false,
      date: '01/05/2025',
      memoNo: '10',
      toBranch: 'To Branch 4',
      vehicle: 'Vehicle 4',
      driver: 'Driver 4',
      agent: 'Agent 4',
      hire: 'Hire 4',
      cashBank: 'Bank',
      center: 'Center 4',
      packaging: 'Bag',
      description: 'Sample 4',
      article: 12,
      freightBy: 'TBB',
      fromCity: 'BANGALORE',
      toPay: 300.00,
      paid: 150.00,
      narration: 'Test Memo 4',
      memoFreight: 450.00,
      lrRows: [
        {
          centerName: 'Center 4',
          lrNo: '1005',
          date: '01/05/2025',
          packaging: 'Bag',
          description: 'Sample 4',
          article: 12,
          freightBy: 'TBB',
          fromCity: 'BANGALORE',
          toCity: 'MUMBAI',
          consignee: 'Consignee 5',
          acWeight: 180,
          weight: 180,
          freight: 450,
        },
      ],
      totalArticle: 12,
      totalAcWeight: 180,
      totalWeight: 180,
      totalFreight: 450,
    },
    {
      selected: false,
      audited: false,
      date: '02/05/2025',
      memoNo: '11',
      toBranch: 'To Branch 5',
      vehicle: 'Vehicle 5',
      driver: 'Driver 5',
      agent: 'Agent 5',
      hire: 'Hire 5',
      cashBank: 'Cash',
      center: 'Center 5',
      packaging: 'Box',
      description: 'Sample 5',
      article: 15,
      freightBy: 'TBB',
      fromCity: 'MUMBAI',
      toPay: 250.00,
      paid: 125.00,
      narration: 'Test Memo 5',
      memoFreight: 375.00,
      lrRows: [
        {
          centerName: 'Center 5',
          lrNo: '1006',
          date: '02/05/2025',
          packaging: 'Box',
          description: 'Sample 5',
          article: 15,
          freightBy: 'TBB',
          fromCity: 'MUMBAI',
          toCity: 'DELHI',
          consignee: 'Consignee 6',
          acWeight: 200,
          weight: 200,
          freight: 375,
        },
      ],
      totalArticle: 15,
      totalAcWeight: 200,
      totalWeight: 200,
      totalFreight: 375,
    },
    {
      selected: false,
      audited: true,
      date: '03/05/2025',
      memoNo: '12',
      toBranch: 'To Branch 6',
      vehicle: 'Vehicle 6',
      driver: 'Driver 6',
      agent: 'Agent 6',
      hire: 'Hire 6',
      cashBank: 'Bank',
      center: 'Center 6',
      packaging: 'Carton',
      description: 'Sample 6',
      article: 7,
      freightBy: 'TBB',
      fromCity: 'DELHI',
      toPay: 180.00,
      paid: 90.00,
      narration: 'Test Memo 6',
      memoFreight: 270.00,
      lrRows: [
        {
          centerName: 'Center 6',
          lrNo: '1007',
          date: '03/05/2025',
          packaging: 'Carton',
          description: 'Sample 6',
          article: 7,
          freightBy: 'TBB',
          fromCity: 'DELHI',
          toCity: 'PUNE',
          consignee: 'Consignee 7',
          acWeight: 140,
          weight: 140,
          freight: 270,
        },
      ],
      totalArticle: 7,
      totalAcWeight: 140,
      totalWeight: 140,
      totalFreight: 270,
    },
    {
      selected: false,
      audited: false,
      date: '04/05/2025',
      memoNo: '13',
      toBranch: 'To Branch 7',
      vehicle: 'Vehicle 7',
      driver: 'Driver 7',
      agent: 'Agent 7',
      hire: 'Hire 7',
      cashBank: 'Cash',
      center: 'Center 7',
      packaging: 'Bag',
      description: 'Sample 7',
      article: 9,
      freightBy: 'TBB',
      fromCity: 'PUNE',
      toPay: 220.00,
      paid: 110.00,
      narration: 'Test Memo 7',
      memoFreight: 330.00,
      lrRows: [
        {
          centerName: 'Center 7',
          lrNo: '1008',
          date: '04/05/2025',
          packaging: 'Bag',
          description: 'Sample 7',
          article: 9,
          freightBy: 'TBB',
          fromCity: 'PUNE',
          toCity: 'BANGALORE',
          consignee: 'Consignee 8',
          acWeight: 160,
          weight: 160,
          freight: 330,
        },
      ],
      totalArticle: 9,
      totalAcWeight: 160,
      totalWeight: 160,
      totalFreight: 330,
    },
    {
      selected: false,
      audited: false,
      date: '05/05/2025',
      memoNo: '14',
      toBranch: 'To Branch 8',
      vehicle: 'Vehicle 8',
      driver: 'Driver 8',
      agent: 'Agent 8',
      hire: 'Hire 8',
      cashBank: 'Bank',
      center: 'Center 8',
      packaging: 'Box',
      description: 'Sample 8',
      article: 11,
      freightBy: 'TBB',
      fromCity: 'BANGALORE',
      toPay: 280.00,
      paid: 140.00,
      narration: 'Test Memo 8',
      memoFreight: 420.00,
      lrRows: [
        {
          centerName: 'Center 8',
          lrNo: '1009',
          date: '05/05/2025',
          packaging: 'Box',
          description: 'Sample 8',
          article: 11,
          freightBy: 'TBB',
          fromCity: 'BANGALORE',
          toCity: 'MUMBAI',
          consignee: 'Consignee 9',
          acWeight: 170,
          weight: 170,
          freight: 420,
        },
      ],
      totalArticle: 11,
      totalAcWeight: 170,
      totalWeight: 170,
      totalFreight: 420,
    },
    {
      selected: false,
      audited: true,
      date: '06/05/2025',
      memoNo: '15',
      toBranch: 'To Branch 9',
      vehicle: 'Vehicle 9',
      driver: 'Driver 9',
      agent: 'Agent 9',
      hire: 'Hire 9',
      cashBank: 'Cash',
      center: 'Center 9',
      packaging: 'Carton',
      description: 'Sample 9',
      article: 6,
      freightBy: 'TBB',
      fromCity: 'MUMBAI',
      toPay: 190.00,
      paid: 95.00,
      narration: 'Test Memo 9',
      memoFreight: 285.00,
      lrRows: [
        {
          centerName: 'Center 9',
          lrNo: '1010',
          date: '06/05/2025',
          packaging: 'Carton',
          description: 'Sample 9',
          article: 6,
          freightBy: 'TBB',
          fromCity: 'MUMBAI',
          toCity: 'DELHI',
          consignee: 'Consignee 10',
          acWeight: 130,
          weight: 130,
          freight: 285,
        },
      ],
      totalArticle: 6,
      totalAcWeight: 130,
      totalWeight: 130,
      totalFreight: 285,
    },
    {
      selected: false,
      audited: false,
      date: '07/05/2025',
      memoNo: '16',
      toBranch: 'To Branch 10',
      vehicle: 'Vehicle 10',
      driver: 'Driver 10',
      agent: 'Agent 10',
      hire: 'Hire 10',
      cashBank: 'Bank',
      center: 'Center 10',
      packaging: 'Bag',
      description: 'Sample 10',
      article: 14,
      freightBy: 'TBB',
      fromCity: 'DELHI',
      toPay: 260.00,
      paid: 130.00,
      narration: 'Test Memo 10',
      memoFreight: 390.00,
      lrRows: [
        {
          centerName: 'Center 10',
          lrNo: '1011',
          date: '07/05/2025',
          packaging: 'Bag',
          description: 'Sample 10',
          article: 14,
          freightBy: 'TBB',
          fromCity: 'DELHI',
          toCity: 'PUNE',
          consignee: 'Consignee 11',
          acWeight: 190,
          weight: 190,
          freight: 390,
        },
      ],
      totalArticle: 14,
      totalAcWeight: 190,
      totalWeight: 190,
      totalFreight: 390,
    },
  ];

  const columns = [
    { label: 'A', field: 'selected' },
    { label: 'Audited', field: 'audited' },
    { label: 'Date', field: 'date' },
    { label: 'Memo No', field: 'memoNo' },
    { label: 'To Branch', field: 'toBranch' },
    { label: 'Vehicle', field: 'vehicle' },
    { label: 'Driver', field: 'driver' },
    { label: 'Agent', field: 'agent' },
    { label: 'Hire', field: 'hire' },
    { label: 'Cash/Bank', field: 'cashBank' },
    { label: 'Center', field: 'center' },
    { label: 'Packaging', field: 'packaging' },
    { label: 'Description', field: 'description' },
    { label: 'Article', field: 'article' },
    { label: 'Freight By', field: 'freightBy' },
    { label: 'From City', field: 'fromCity' },
    { label: 'To Pay', field: 'toPay' },
    { label: 'Paid', field: 'paid' },
    { label: 'Narration', field: 'narration' },
    { label: 'Memo Freight', field: 'memoFreight' },
    { label: 'Total Article', field: 'totalArticle' },
    { label: 'Total Ac. Weight', field: 'totalAcWeight' },
    { label: 'Total Weight', field: 'totalWeight' },
    { label: 'Total Freight', field: 'totalFreight' },
  ];

  const numericFields = ['article', 'toPay', 'paid', 'memoFreight', 'totalArticle', 'totalAcWeight', 'totalWeight', 'totalFreight'];



  const windowConfig = {
    initialState: {
      id: '',
      selected: false,
      audited: false,
      date: new Date().toLocaleDateString('en-GB').split('/').join('/'),
      memoNo: '',
      toBranch: '',
      vehicle: '',
      driver: '',
      agent: '',
      hire: '',
      cashBank: '',
      center: '',
      packaging: '',
      description: '',
      article: 0,
      freightBy: '',
      fromCity: '',
      toCity: '',
      toPay: 0,
      paid: 0,
      narration: '',
      memoFreight: 0,
      lrRows: [
        {
          centerName: '',
          lrNo: '',
          date: '',
          packaging: '',
          description: '',
          article: 0,
          freightBy: '',
          fromCity: '',
          toCity: '',
          consignee: '',
          acWeight: 0,
          weight: 0,
          freight: 0,
        },
      ],
      totalArticle: 0,
      totalAcWeight: 0,
      totalWeight: 0,
      totalFreight: 0,
      city: '',
      balance: 0,
      paymentType: '',
      advanced: 0,
      vehicleNo: '',
      branch: '',
    },
    fieldMapping: (entry) => ({
      id: entry.id || '',
      selected: entry.selected || false,
      audited: entry.audited || false,
      date: entry.date || '',
      memoNo: entry.memoNo || '',
      toBranch: entry.toBranch || '',
      vehicle: entry.vehicle || '',
      driver: entry.driver || '',
      agent: entry.agent || '',
      hire: entry.hire || '',
      cashBank: entry.cashBank || '',
      center: entry.center || '',
      packaging: entry.packaging || '',
      description: entry.description || '',
      article: parseInt(entry.article) || 0,
      freightBy: entry.freightBy || '',
      fromCity: entry.fromCity || '',
      toCity: entry.toCity || '',
      toPay: parseFloat(entry.toPay) || 0,
      paid: parseFloat(entry.paid) || 0,
      narration: entry.narration || '',
      memoFreight: parseFloat(entry.memoFreight) || 0,
      lrRows: entry.lrRows || [],
      totalArticle: parseInt(entry.totalArticle) || 0,
      totalAcWeight: parseFloat(entry.totalAcWeight) || 0,
      totalWeight: parseFloat(entry.totalWeight) || 0,
      totalFreight: parseFloat(entry.totalFreight) || 0,
      city: entry.city || '',
      balance: parseFloat(entry.balance) || 0,
      paymentType: entry.paymentType || '',
      advanced: parseFloat(entry.advanced) || 0,
      vehicleNo: entry.vehicleNo || '',
      branch: entry.branch || '',
    }),
  };

  return (
    <TableLayout
      title="List of Memo"
      columns={columns}
      initialData={initialData}
      numericFields={numericFields}
     
      windowConfig={windowConfig}
      componentType="memo"
      showAdd={true}
      showEdit={true}
      showView={true}
      showDelete={true}
      showRefresh={true}
      showPrint={true}
      showAudit={true}
      showField={true}
      showExportExcel={true}
      showExportPDF={true}
    />
  );
};

export default ListOfMemo;