import React from 'react';
import TableLayout from './TableLayout';


const ListOfTransporterBill = () => {
  const initialData = [
    {
      selected: false,
      audited: false,
      billNo: 'BILL001',
      billDate: '01/04/2025',
      accountName: 'XYZ Transport',
      totalAmount: 12000.00,
      taxType: 'GST',
      billType: 'Standard',
      salesAccount: 'Sales - General',
      totalArticle: 10,
      totalWeight: 500,
      taxableAmount: 11428.57,
      totalGST: 571.43,
      totalCGST: 285.71,
      totalSGST: 285.71,
      totalIGST: 0,
      itemFreight: 12000.00,
      expenseName: 'Service Charge',
      expenseAccount: 'Expense - Service',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL002',
      billDate: '02/04/2025',
      accountName: 'ABC Logistics',
      totalAmount: 18000.00,
      taxType: 'VAT',
      billType: 'Proforma',
      salesAccount: 'Sales - Retail',
      totalArticle: 15,
      totalWeight: 750,
      taxableAmount: 17142.86,
      totalGST: 857.14,
      totalCGST: 0,
      totalSGST: 0,
      totalIGST: 857.14,
      itemFreight: 18000.00,
      expenseName: 'Insurance',
      expenseAccount: 'Expense - Insurance',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL003',
      billDate: '03/04/2025',
      accountName: 'Quick Cargo',
      totalAmount: 15000.00,
      taxType: 'GST',
      billType: 'Standard',
      salesAccount: 'Sales - Wholesale',
      totalArticle: 20,
      totalWeight: 1000,
      taxableAmount: 14285.71,
      totalGST: 714.29,
      totalCGST: 357.14,
      totalSGST: 357.14,
      totalIGST: 0,
      itemFreight: 15000.00,
      expenseName: 'Packaging Fee',
      expenseAccount: 'Expense - General',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL004',
      billDate: '04/04/2025',
      accountName: 'Global Shipping',
      totalAmount: 22000.00,
      taxType: 'VAT',
      billType: 'Proforma',
      salesAccount: 'Sales - Services',
      totalArticle: 12,
      totalWeight: 600,
      taxableAmount: 20952.38,
      totalGST: 1047.62,
      totalCGST: 0,
      totalSGST: 0,
      totalIGST: 1047.62,
      itemFreight: 22000.00,
      expenseName: 'Other',
      expenseAccount: 'Expense - General',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL005',
      billDate: '05/04/2025',
      accountName: 'Speedy Movers',
      totalAmount: 9500.00,
      taxType: 'GST',
      billType: 'Standard',
      salesAccount: 'Sales - General',
      totalArticle: 8,
      totalWeight: 400,
      taxableAmount: 9047.62,
      totalGST: 452.38,
      totalCGST: 226.19,
      totalSGST: 226.19,
      totalIGST: 0,
      itemFreight: 9500.00,
      expenseName: 'Service Charge',
      expenseAccount: 'Expense - Service',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL006',
      billDate: '06/04/2025',
      accountName: 'Safe Haul',
      totalAmount: 13500.00,
      taxType: 'VAT',
      billType: 'Proforma',
      salesAccount: 'Sales - Retail',
      totalArticle: 18,
      totalWeight: 900,
      taxableAmount: 12857.14,
      totalGST: 642.86,
      totalCGST: 0,
      totalSGST: 0,
      totalIGST: 642.86,
      itemFreight: 13500.00,
      expenseName: 'Insurance',
      expenseAccount: 'Expense - Insurance',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL007',
      billDate: '07/04/2025',
      accountName: 'Metro Freight',
      totalAmount: 25000.00,
      taxType: 'GST',
      billType: 'Standard',
      salesAccount: 'Sales - Wholesale',
      totalArticle: 14,
      totalWeight: 700,
      taxableAmount: 23809.52,
      totalGST: 1190.48,
      totalCGST: 595.24,
      totalSGST: 595.24,
      totalIGST: 0,
      itemFreight: 25000.00,
      expenseName: 'Packaging Fee',
      expenseAccount: 'Expense - General',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL008',
      billDate: '08/04/2025',
      accountName: 'Oceanic Logistics',
      totalAmount: 17500.00,
      taxType: 'VAT',
      billType: 'Proforma',
      salesAccount: 'Sales - Services',
      totalArticle: 16,
      totalWeight: 800,
      taxableAmount: 16666.67,
      totalGST: 833.33,
      totalCGST: 0,
      totalSGST: 0,
      totalIGST: 833.33,
      itemFreight: 17500.00,
      expenseName: 'Other',
      expenseAccount: 'Expense - General',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL009',
      billDate: '09/04/2025',
      accountName: 'Air Express',
      totalAmount: 21000.00,
      taxType: 'GST',
      billType: 'Standard',
      salesAccount: 'Sales - General',
      totalArticle: 22,
      totalWeight: 1100,
      taxableAmount: 20000.00,
      totalGST: 1000.00,
      totalCGST: 500.00,
      totalSGST: 500.00,
      totalIGST: 0,
      itemFreight: 21000.00,
      expenseName: 'Service Charge',
      expenseAccount: 'Expense - Service',
      expenseRate: 0,
      expenseAmount: 0,
    },
    {
      selected: false,
      audited: false,
      billNo: 'BILL010',
      billDate: '10/04/2025',
      accountName: 'Nationwide Transport',
      totalAmount: 19500.00,
      taxType: 'VAT',
      billType: 'Proforma',
      salesAccount: 'Sales - Retail',
      totalArticle: 9,
      totalWeight: 450,
      taxableAmount: 18571.43,
      totalGST: 928.57,
      totalCGST: 0,
      totalSGST: 0,
      totalIGST: 928.57,
      itemFreight: 19500.00,
      expenseName: 'Insurance',
      expenseAccount: 'Expense - Insurance',
      expenseRate: 0,
      expenseAmount: 0,
    },
  ];

  const columns = [
    { label: 'A', field: 'selected' },
    { label: 'Audited', field: 'audited' },
    { label: 'Bill No', field: 'billNo' },
    { label: 'Bill Date', field: 'billDate' },
    { label: 'Account Name', field: 'accountName' },
    { label: 'Total Amount', field: 'totalAmount' },
  ];

  const numericFields = [
    'totalAmount',
    'article',
    'weight',
    'rate',
    'charge1',
    'charge2',
    'totalFreight',
    'totalArticle',
    'totalWeight',
    'amount',
    'balance',
    'taxableAmount',
    'totalGST',
    'totalCGST',
    'totalSGST',
    'totalIGST',
    'itemFreight',
    'expenseRate',
    'expenseAmount',
  ];

  const fieldConfig = {
    cashDebit: { options: ['Cash', 'Debit', 'Credit'] },
    taxType: { options: ['GST', 'VAT', 'TAX FREE'] },
    billType: { options: ['Standard', 'Proforma'] },
    salesAccount: {
      options: ['Sales - General', 'Sales - Retail', 'Sales - Wholesale', 'Sales - Services'],
    },
    sortedAscending: {
      options: ['Yes', 'No'],
    },
    expenseName: {
      options: ['Service Charge', 'Packaging Fee', 'Insurance', 'Other'],
    },
    expenseAccount: {
      options: ['Expense - General', 'Expense - Service', 'Expense - Insurance'],
    },
  };

  const windowConfig = {
    initialState: {
      selected: false,
      audited: false,
      billNo: '',
      billDate: new Date().toLocaleDateString('en-GB').split('/').join('/'),
      accountName: '',
      totalAmount: 0,
      cashDebit: 'Debit',
      billType: 'Lr',
      party: '',
      docNo: '',
      docDate: '',
      balance: 0,
      taxType: 'GST',
      salesAccount: 'Sales - General',
      hsnSac: '',
      centerName: '',
      lrNo: '',
      lrDate: '',
      consigner: '',
      consignee: '',
      truckNo: '',
      weight: 0,
      fromCity: '',
      toCity: '',
      sortedAscending: 'Yes',
      article: 0,
      taxableAmount: 0,
      totalGST: 0,
      totalCGST: 0,
      totalSGST: 0,
      totalIGST: 0,
      itemFreight: 0,
      narration: '',
      expenseName: '',
      expenseAccount: '',
      expenseRate: 0,
      expenseAmount: 0,
      rate: 0,
      amount: 0,
      totalArticle: 0,
      totalWeight: 0,
      charge1: 0,
      charge2: 0,
      subTotal: 0,
      gst: 0,
      cgst: 0,
      sgst: 0,
      igst: 0,
      totalFreight: 0,
      rows: [],
    },
    fieldMapping: (entry) => ({
      selected: entry.selected || false,
      audited: entry.audited || false,
      billNo: entry.billNo || '',
      billDate: entry.billDate || '',
      accountName: entry.accountName || '',
      totalAmount: parseFloat(entry.totalAmount) || 0,
      cashDebit: entry.cashDebit || '',
      billType: entry.billType || '',
      party: entry.party || '',
      docNo: entry.docNo || '',
      docDate: entry.docDate || '',
      balance: parseFloat(entry.balance) || 0,
      taxType: entry.taxType || '',
      salesAccount: entry.salesAccount || '',
      hsnSac: entry.hsnSac || '',
      centerName: entry.centerName || '',
      lrNo: entry.lrNo || '',
      lrDate: entry.lrDate || '',
      consigner: entry.consigner || '',
      consignee: entry.consignee || '',
      truckNo: entry.truckNo || '',
      weight: parseFloat(entry.weight) || 0,
      fromCity: entry.fromCity || '',
      toCity: entry.toCity || '',
      sortedAscending: entry.sortedAscending || '',
      article: parseInt(entry.article) || 0,
      taxableAmount: parseFloat(entry.taxableAmount) || 0,
      totalGST: parseFloat(entry.totalGST) || 0,
      totalCGST: parseFloat(entry.totalCGST) || 0,
      totalSGST: parseFloat(entry.totalSGST) || 0,
      totalIGST: parseFloat(entry.totalIGST) || 0,
      itemFreight: parseFloat(entry.itemFreight) || 0,
      narration: entry.narration || '',
      expenseName: entry.expenseName || '',
      expenseAccount: entry.expenseAccount || '',
      expenseRate: parseFloat(entry.expenseRate) || 0,
      expenseAmount: parseFloat(entry.expenseAmount) || 0,
      rate: parseFloat(entry.rate) || 0,
      amount: parseFloat(entry.amount) || 0,
      totalArticle: parseInt(entry.totalArticle) || 0,
      totalWeight: parseFloat(entry.totalWeight) || 0,
      charge1: parseFloat(entry.charge1) || 0,
      charge2: parseFloat(entry.charge2) || 0,
      subTotal: parseFloat(entry.subTotal) || 0,
      gst: parseFloat(entry.gst) || 0,
      cgst: parseFloat(entry.cgst) || 0,
      sgst: parseFloat(entry.sgst) || 0,
      igst: parseFloat(entry.igst) || 0,
      totalFreight: parseFloat(entry.totalFreight) || 0,
      rows: entry.rows || [],
    }),
  };

  return (
    <TableLayout
      title="List of Transporter Bill"
      columns={columns}
      initialData={initialData}
      numericFields={numericFields}
      fieldConfig={fieldConfig}
      windowConfig={windowConfig}
      componentType="transportBill"
      showAdd={true}
      showEdit={true}
      showView={true}
      showDelete={true}
      showRefresh={true}
      showPrint={true}
      showAudit={true}
      showField={true}
      showExportExcel={true}
      showExportPDF={true}
      
    />
  );
};

export default ListOfTransporterBill;