import React from 'react';
import ReportLayout from './ReportLayout';

const containerReturnData = [
  {
    'Current Date': '20/02/2025',
    'Delivery Order No.': 'DOABQ00107497',
    'Voyage No.': '04JJOE1MA',
    'Vessel Name': 'CMA CGM',
    'BillOfLading': 'MAEU245321299',
    'ContainerNo': 'FCIU4518976',
    'Seal No.': 'BOLT51213684',
    'Qty.': 1,
    'Container Type': '20 DV/GP/ST',
    'Expiry Date': '20/02/2025',
    'Status': 'Processing',
    'POL': 'NEW YORK/US',
    'POD': 'MAPUTO/MZ',
    'Delivery By': 'Saide Joaquim',
    'Delivery Terminal': 'Terminal A',
    'Deliver To': 'GMS Depot',
    'Trucking Company': 'ZimTrans Logistics',
    'Remarks': 'Pending offload'
  },
  {
    'Current Date': '20/02/2025',
    'Delivery Order No.': 'DOABQ00107497',
    'Voyage No.': '',
    'Vessel Name': 'MSC',
    'BillOfLading': 'MAEU245321299',
    'ContainerNo': 'IPXU2156420',
    'Seal No.': 'L6008074',
    'Qty.': 1,
    'Container Type': '20 DV/GP/ST',
    'Expiry Date': '20/02/2025',
    'Status': 'Delayed',
    'POL': 'SURAT/IN',
    'POD': 'BEIRA/MZ',
    'Delivery By': 'João Pinto',
    'Delivery Terminal': 'Terminal B',
    'Deliver To': 'Warehouse Z',
    'Trucking Company': 'MSC Carriers',
    'Remarks': 'Seal mismatch at gate'
  },
  {
    'Current Date': '20/02/2025',
    'Delivery Order No.': 'DOABQ00107497',
    'Voyage No.': '',
    'Vessel Name': 'MAERSHK',
    'BillOfLading': 'MAEU245321299',
    'ContainerNo': 'TEMU5425050',
    'Seal No.': 'L6003660',
    'Qty.': 2,
    'Container Type': '20 DV/GP/ST',
    'Expiry Date': '20/02/2025',
    'Status': 'Delivered',
    'POL': 'DURBAN/SA',
    'POD': 'MAPUTO/MZ',
    'Delivery By': 'Carlos M.',
    'Delivery Terminal': 'Terminal C',
    'Deliver To': 'ETG Main WH',
    'Trucking Company': 'Maersk Trucking',
    'Remarks': ''
  },
  {
    'Current Date': '21/02/2025',
    'Delivery Order No.': 'DOABQ00107498',
    'Voyage No.': '08HKJDK12',
    'Vessel Name': 'HAPAG-LLOYD',
    'BillOfLading': 'HLX1234567',
    'ContainerNo': 'HLXU9988776',
    'Seal No.': 'L6003988',
    'Qty.': 1,
    'Container Type': '40 HC',
    'Expiry Date': '21/02/2025',
    'Status': 'Delivered',
    'POL': 'FELIXSTOWE/UK',
    'POD': 'BEIRA/MZ',
    'Delivery By': 'Rafael dos Santos',
    'Delivery Terminal': 'Terminal A',
    'Deliver To': 'Client A Storage',
    'Trucking Company': 'HLX Haulage',
    'Remarks': 'N/A'
  },
  {
    'Current Date': '22/02/2025',
    'Delivery Order No.': 'DOABQ00107499',
    'Voyage No.': '99TYUE92',
    'Vessel Name': 'EVERGREEN',
    'BillOfLading': 'EGL2233445',
    'ContainerNo': 'EGLU4455667',
    'Seal No.': 'L6011223',
    'Qty.': 1,
    'Container Type': '20 DV',
    'Expiry Date': '22/02/2025',
    'Status': 'Processing',
    'POL': 'SHANGHAI/CN',
    'POD': 'MAPUTO/MZ',
    'Delivery By': 'Ana Moisés',
    'Delivery Terminal': 'Terminal B',
    'Deliver To': 'Retail Hub',
    'Trucking Company': 'Ever Haul Ltd.',
    'Remarks': 'Under verification'
  },
  {
    'Current Date': '22/02/2025',
    'Delivery Order No.': 'DOABQ00107500',
    'Voyage No.': '73PLME33',
    'Vessel Name': 'COSCO',
    'BillOfLading': 'COS5566778',
    'ContainerNo': 'COSU7788990',
    'Seal No.': 'L6044999',
    'Qty.': 3,
    'Container Type': '40 OT',
    'Expiry Date': '22/02/2025',
    'Status': 'Delayed',
    'POL': 'NINGBO/CN',
    'POD': 'BEIRA/MZ',
    'Delivery By': 'Daniel J.',
    'Delivery Terminal': 'Terminal C',
    'Deliver To': 'Zambezi WH',
    'Trucking Company': 'COSCO Logistics',
    'Remarks': 'Truck breakdown en route'
  },
  {
    'Current Date': '23/02/2025',
    'Delivery Order No.': 'DOABQ00107501',
    'Voyage No.': '19JKSHD21',
    'Vessel Name': 'ZIM',
    'BillOfLading': 'ZIM1122334',
    'ContainerNo': 'ZIMU3344556',
    'Seal No.': 'L6055122',
    'Qty.': 2,
    'Container Type': '20 DV',
    'Expiry Date': '23/02/2025',
    'Status': 'Delivered',
    'POL': 'ANTWERP/BE',
    'POD': 'MAPUTO/MZ',
    'Delivery By': 'Fatima D.',
    'Delivery Terminal': 'Terminal A',
    'Deliver To': 'Agro Exports',
    'Trucking Company': 'ZIM Movers',
    'Remarks': ''
  },
  {
    'Current Date': '24/02/2025',
    'Delivery Order No.': 'DOABQ00107502',
    'Voyage No.': '12MOPAQ33',
    'Vessel Name': 'ONE',
    'BillOfLading': 'ONE8877665',
    'ContainerNo': 'ONEU7766554',
    'Seal No.': 'L6066333',
    'Qty.': 1,
    'Container Type': '20 DV/GP/ST',
    'Expiry Date': '24/02/2025',
    'Status': 'Processing',
    'POL': 'SINGAPORE/SG',
    'POD': 'MAPUTO/MZ',
    'Delivery By': 'Simão P.',
    'Delivery Terminal': 'Terminal B',
    'Deliver To': 'TechZone',
    'Trucking Company': 'ONE Logistics',
    'Remarks': 'Awaiting clearance'
  },
  {
    'Current Date': '25/02/2025',
    'Delivery Order No.': 'DOABQ00107503',
    'Voyage No.': '88PLSKQ90',
    'Vessel Name': 'MAERSK',
    'BillOfLading': 'MAEU9998887',
    'ContainerNo': 'MSCU8899776',
    'Seal No.': 'L6077444',
    'Qty.': 1,
    'Container Type': '40 DV',
    'Expiry Date': '25/02/2025',
    'Status': 'Delayed',
    'POL': 'ROTTERDAM/NL',
    'POD': 'MAPUTO/MZ',
    'Delivery By': 'Carlos A.',
    'Delivery Terminal': 'Terminal C',
    'Deliver To': 'Blue Freight Hub',
    'Trucking Company': 'Maersk Dispatch',
    'Remarks': 'Awaiting truck'
  },
  {
    'Current Date': '26/02/2025',
    'Delivery Order No.': 'DOABQ00107504',
    'Voyage No.': '32ASDPO11',
    'Vessel Name': 'MSC',
    'BillOfLading': 'MSC4443332',
    'ContainerNo': 'MSCU1122334',
    'Seal No.': 'L6088555',
    'Qty.': 2,
    'Container Type': '40 HC',
    'Expiry Date': '26/02/2025',
    'Status': 'Delivered',
    'POL': 'BUSAN/KR',
    'POD': 'MAPUTO/MZ',
    'Delivery By': 'Joaquim Manuel',
    'Delivery Terminal': 'Terminal A',
    'Deliver To': 'Port Distribution Hub',
    'Trucking Company': 'MSC Transporters',
    'Remarks': 'N/A'
  }
];

const headers = [
  'Current Date',
  'Delivery Order No.',
  'Voyage No.',
  'Vessel Name',
  'Bill of Lading',
  'ContainerNo',
  'Seal No.',
  'Qty.',
  'Container Type',
  'Expiry Date',
  'Status',
  'POL',
  'POD',
  'Delivery By',
  'Delivery Terminal',
  'Deliver To',
  'Trucking Company',
  'Remarks'
];

const ContainerReturnReport = ({ theme }) => {
  return (
    <ReportLayout
      data={containerReturnData}
      headers={headers}
      title="Containers Return Plan Report"
      theme={theme}
    />
  );
};

export default ContainerReturnReport;
