import React from 'react';
import ReportLayout from './ReportLayout';

const warehouseData = [
  {
    FileNo: '00007/UVC/25',
    warehouseEntryDate: '03/01/2025',
    vesselName: 'CMA-CGM',
    BillOfLading: 'SEL1793950',
    ContainerNo: 'ECMU1704969',
    category: 'I',
    freightKind: 'F',
    qty: 1,
    containerType: '20 DV/GP/ST',
    cargoDescription: 'HYDROGEN PEROXIDE',
    cargoMovements: 'At Storage',
    pol: 'BUSAN',
    pod: 'BEIRA',
    destination: 'Beira Depot',
    clients: 'ETG Zimbabwe',
    portDueDate: '10/01/2025',
    status: 'Pending',
    truckingCompany: 'ZIM Transports',
    portEntryDate: '08/01/2025',
    lastFreeDay: '13/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 4,
    storageDays: 2,
    remarks: 'None',
  },
  {
    FileNo: '00008/UVC/25',
    warehouseEntryDate: '04/01/2025',
    vesselName: 'MAERSK LINE',
    BillOfLading: 'MAEU1234567',
    ContainerNo: 'MSCU1234567',
    category: 'E',
    freightKind: 'C',
    qty: 2,
    containerType: '40 HC',
    cargoDescription: 'AGRICULTURAL EQUIPMENT',
    cargoMovements: 'Unloading',
    pol: 'ROTTERDAM',
    pod: 'MAPUTO',
    destination: 'Warehouse A',
    clients: 'SAS Freight',
    portDueDate: '12/01/2025',
    status: 'Delivered',
    truckingCompany: 'Fast Movers Ltd.',
    portEntryDate: '10/01/2025',
    lastFreeDay: '15/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 2,
    storageDays: 0,
    remarks: 'Fast track',
  },
  {
    FileNo: '00009/UVC/25',
    warehouseEntryDate: '05/01/2025',
    vesselName: 'HAPAG-LLOYD',
    BillOfLading: 'HLX9876543',
    ContainerNo: 'HLXU9876543',
    category: 'I',
    freightKind: 'F',
    qty: 3,
    containerType: '20 DV',
    cargoDescription: 'COTTON BALES',
    cargoMovements: 'In Transit',
    pol: 'HAMBURG',
    pod: 'BEIRA',
    destination: 'Factory Z',
    clients: 'Global Imports',
    portDueDate: '13/01/2025',
    status: 'Dispatched',
    truckingCompany: 'Beira Logistics',
    portEntryDate: '11/01/2025',
    lastFreeDay: '16/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 3,
    storageDays: 1,
    remarks: 'N/A',
  },
  {
    FileNo: '00010/UVC/25',
    warehouseEntryDate: '06/01/2025',
    vesselName: 'MSC',
    BillOfLading: 'MSC5647382',
    ContainerNo: 'MSCU5647382',
    category: 'I',
    freightKind: 'F',
    qty: 1,
    containerType: '40 OT',
    cargoDescription: 'INDUSTRIAL MACHINERY',
    cargoMovements: 'Delivered',
    pol: 'GENOVA',
    pod: 'MAPUTO',
    destination: 'Zone B',
    clients: 'ETG Zambia',
    portDueDate: '14/01/2025',
    status: 'Completed',
    truckingCompany: 'MSC Haulers',
    portEntryDate: '12/01/2025',
    lastFreeDay: '17/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 1,
    storageDays: 1,
    remarks: 'Delivered on time',
  },
  {
    FileNo: '00011/UVC/25',
    warehouseEntryDate: '07/01/2025',
    vesselName: 'COSCO',
    BillOfLading: 'COS0987654',
    ContainerNo: 'COSU0987654',
    category: 'E',
    freightKind: 'C',
    qty: 4,
    containerType: '20 RF',
    cargoDescription: 'FROZEN FOODS',
    cargoMovements: 'At Storage',
    pol: 'QINGDAO',
    pod: 'BEIRA',
    destination: 'Cold Room',
    clients: 'ZIM Logistics',
    portDueDate: '15/01/2025',
    status: 'Pending',
    truckingCompany: 'Ice Movers',
    portEntryDate: '13/01/2025',
    lastFreeDay: '18/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 3,
    storageDays: 0,
    remarks: 'Reefer connected',
  },
  {
    FileNo: '00012/UVC/25',
    warehouseEntryDate: '08/01/2025',
    vesselName: 'EVERGREEN',
    BillOfLading: 'EGL2468135',
    ContainerNo: 'EGLU2468135',
    category: 'I',
    freightKind: 'F',
    qty: 2,
    containerType: '20 DV',
    cargoDescription: 'FURNITURE',
    cargoMovements: 'Unloading',
    pol: 'KAOHSIUNG',
    pod: 'MAPUTO',
    destination: 'Warehouse B',
    clients: 'Trinity Holdings',
    portDueDate: '16/01/2025',
    status: 'Ongoing',
    truckingCompany: 'Furnish Movers',
    portEntryDate: '14/01/2025',
    lastFreeDay: '19/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 2,
    storageDays: 0,
    remarks: '-',
  },
  {
    FileNo: '00013/UVC/25',
    warehouseEntryDate: '09/01/2025',
    vesselName: 'YANG MING',
    BillOfLading: 'YML1357924',
    ContainerNo: 'YMLU1357924',
    category: 'I',
    freightKind: 'F',
    qty: 3,
    containerType: '40 HC',
    cargoDescription: 'TEXTILES',
    cargoMovements: 'At Storage',
    pol: 'SHENZHEN',
    pod: 'BEIRA',
    destination: 'Garment Hub',
    clients: 'Oceanic Traders',
    portDueDate: '17/01/2025',
    status: 'Delayed',
    truckingCompany: 'Beira Haul',
    portEntryDate: '15/01/2025',
    lastFreeDay: '20/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 3,
    storageDays: 1,
    remarks: 'Awaiting truck',
  },
  {
    FileNo: '00014/UVC/25',
    warehouseEntryDate: '10/01/2025',
    vesselName: 'ZIM',
    BillOfLading: 'ZIM1123581',
    ContainerNo: 'ZIMU1123581',
    category: 'E',
    freightKind: 'C',
    qty: 2,
    containerType: '20 DV',
    cargoDescription: 'CONSTRUCTION MATERIAL',
    cargoMovements: 'In Transit',
    pol: 'HAIFA',
    pod: 'MAPUTO',
    destination: 'Construction Site',
    clients: 'GMS Mozambique',
    portDueDate: '18/01/2025',
    status: 'On Route',
    truckingCompany: 'ZIMTrans',
    portEntryDate: '16/01/2025',
    lastFreeDay: '21/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 1,
    storageDays: 0,
    remarks: 'ETA 2 days',
  },
  {
    FileNo: '00015/UVC/25',
    warehouseEntryDate: '11/01/2025',
    vesselName: 'CMA-CGM',
    BillOfLading: 'SEL1357913',
    ContainerNo: 'ECMU1357913',
    category: 'I',
    freightKind: 'F',
    qty: 1,
    containerType: '40 DV/GP/ST',
    cargoDescription: 'ELECTRONICS',
    cargoMovements: 'Delivered',
    pol: 'SHANGHAI',
    pod: 'BEIRA',
    destination: 'Tech Depot',
    clients: 'Beira Depot',
    portDueDate: '19/01/2025',
    status: 'Delivered',
    truckingCompany: 'TechLog',
    portEntryDate: '17/01/2025',
    lastFreeDay: '22/01/2025',
    freeDaysAllowed: 5,
    dwellDays: 1,
    storageDays: 0,
    remarks: 'No issues',
  },
];


const headers = [
  'File No.',
  'WarehouseEntry Date',
  'Vessel Name',
  'Bill of Lading [BL No.]',
  'Container No.',
  'Category',
  'Freight Kind',
  'Qty.',
  'Container Type',
  'Cargo Description',
  'Cargo Movements',
  'POL',
  'POD',
  'Destination',
  'Clients',
  'Port Due Date',
  'Status',
  'Trucking Company',
  'Port Entry Date',
  'Last Free Day',
  'Free Days Allowed',
  'Dwell Days',
  'Storage Days',
  'Remarks'
];

const WarehouseProcessingReport = ({ theme }) => {
  return (
    <ReportLayout
      data={warehouseData}
      headers={headers}
      title="Container WH Processing Plan Report"
      theme={theme}
    />
  );
};

export default WarehouseProcessingReport;
