import React from 'react';
import ReportLayout from './ReportLayout';

const warehouseStockData = [
  {
    FileNo: '00007/UVC/25',
    whCargoArrivalDate: '03/01/2025',
    whTime: '10:27:52',
    vesselName: 'CMA-CGM',
    BillOfLading: 'SEL1793950',
    ContainerNo: 'ECMU1704969',
    sealNo: 'L6008074',
    qty: 1,
    containerType: '20 DV/GP/ST',
    countryOfOrigin: 'BUSAN/KOREA',
    consignee: 'ETG Zimbabwe',
    cargoExpiryDate: '07/10/2025',
    totalFreeDays: 5,
    warehouseStorageTime: '4 days',
    cargoStatus: 'Delivered',
    cargoDescription: 'Hydrogen Peroxide',
    productClass: 'Chemical',
    containerCargoQty: 54,
    packageType: 'Drums',
    netWeightPerUnit: 25,
    totalNetWeight: 1350,
    grossWeight: 1500,
    totalCargoQty: 54,
    damagedCargo: 'No',
    shortCargo: 'yes',
    previouslyLeftCargoQuantity: 24,
    deliveredTotalCargo: 30,
    totalCargoBalanceLeft: 0,
    balanceCargoOccupiedArea: 2,
    cargoTrucksDeliveryDate: '10/01/2025',
    truckTrailerDetails: 'ALG 855 MC / AI 398 MC',
    remarks: 'Via Mutare'
  },
  {
    FileNo: '00008/UVC/25',
    whCargoArrivalDate: '04/01/2025',
    whTime: '09:15:00',
    vesselName: 'MAERSK',
    BillOfLading: 'MAEU5432100',
    ContainerNo: 'MSCU8765432',
    sealNo: 'L6011223',
    qty: 2,
    containerType: '40 HC',
    countryOfOrigin: 'ROTTERDAM/NL',
    consignee: 'SAS Freight',
    cargoExpiryDate: '07/11/2025',
    totalFreeDays: 6,
    warehouseStorageTime: '3 days',
    cargoStatus: 'In Storage',
    cargoDescription: 'Agro Equipment',
    productClass: 'Machinery',
    containerCargoQty: 20,
    packageType: 'Crates',
    netWeightPerUnit: 100,
    totalNetWeight: 2000,
    grossWeight: 2300,
    totalCargoQty: 20,
    damagedCargo: 'yes',
    shortCargo: 'yes',
    previouslyLeftCargoQuantity: 0,
    deliveredTotalCargo: 0,
    totalCargoBalanceLeft: 20,
    balanceCargoOccupiedArea: 6,
    cargoTrucksDeliveryDate: '',
    truckTrailerDetails: '',
    remarks: ''
  },
  {
    FileNo: '00009/UVC/25',
    whCargoArrivalDate: '05/01/2025',
    whTime: '12:40:11',
    vesselName: 'MSC',
    BillOfLading: 'MSC1112223',
    ContainerNo: 'MSCU3332211',
    sealNo: 'L6098876',
    qty: 3,
    containerType: '40 OT',
    countryOfOrigin: 'HAMBURG/GERMANY',
    consignee: 'Global Imports',
    cargoExpiryDate: '07/12/2025',
    totalFreeDays: 7,
    warehouseStorageTime: '2 days',
    cargoStatus: 'Processing',
    cargoDescription: 'Cotton Bales',
    productClass: 'Agriculture',
    containerCargoQty: 120,
    packageType: 'Bales',
    netWeightPerUnit: 50,
    totalNetWeight: 6000,
    grossWeight: 6300,
    totalCargoQty: 120,
    damagedCargo: 'No',
    shortCargo: 'yes',
    previouslyLeftCargoQuantity: 50,
    deliveredTotalCargo: 30,
    totalCargoBalanceLeft: 38,
    balanceCargoOccupiedArea: 4.5,
    cargoTrucksDeliveryDate: '11/01/2025',
    truckTrailerDetails: 'ALG 860 MC / AI 402 MC',
    remarks: 'Via Machipanda'
  },
  {
    FileNo: '00010/UVC/25',
    whCargoArrivalDate: '06/01/2025',
    whTime: '14:10:35',
    vesselName: 'CMA-CGM',
    BillOfLading: 'CMA7894561',
    ContainerNo: 'CMAU6543210',
    sealNo: 'L6023456',
    qty: 1,
    containerType: '20 RF',
    countryOfOrigin: 'SHANGHAI/CHINA',
    consignee: 'ETG Zambia',
    cargoExpiryDate: '07/15/2025',
    totalFreeDays: 5,
    warehouseStorageTime: '1 day',
    cargoStatus: 'Completed',
    cargoDescription: 'Frozen Fruit',
    productClass: 'Perishable',
    containerCargoQty: 200,
    packageType: 'Boxes',
    netWeightPerUnit: 20,
    totalNetWeight: 4000,
    grossWeight: 4400,
    totalCargoQty: 200,
    damagedCargo: 'yes',
    shortCargo: 'yes',
    previouslyLeftCargoQuantity: 0,
    deliveredTotalCargo: 200,
    totalCargoBalanceLeft: 0,
    balanceCargoOccupiedArea: 3,
    cargoTrucksDeliveryDate: '09/01/2025',
    truckTrailerDetails: 'ALG 861 MC / AI 403 MC',
    remarks: 'Direct delivery'
  }
];


const headers = [
  'File No.',
  'WH Cargo Arrival Date',
  'WH Time',
  'Vessel Name',
  'Bill of Lading',
  'Container No.',
  'Seal No.',
  'Qty.',
  'Container Type',
  'Country of Origin',
  'Consignee',
  'Cargo Expiry Date',
  'Total Free Days',
  'Warehouse Storage Time',
  'Cargo Status',
  'Cargo Description',
  'Product Class',
  "Container's Cargo Qty. [Bags/Barrels/Box/Cans]",
  'Package Type',
  'Net Weight [Per/Unit] Kgs.',
  'Total Net Weight [Kgs.]',
  'Gross Weight [Kgs.]',
  'Total Cargo Qty.  [Bags/Barrels/Box/Cans]',
  'Damaged Cargo',
  'Short Cargo',
  'Previously Left Cargo Quantity',
  'Delivered Total Cargo',
  'Total Cargo Balance Left',
  'Balance Cargo Occupied Area [MTS]',
  'Cargo Trucks Delivery Date',
  'Truck/Trailer Details',
  'Remarks'
];

const WarehouseStockReport = ({ theme }) => {
  return (
    <ReportLayout
      data={warehouseStockData}
      headers={headers}
      title="Warehouse Stock Details Report"
      theme={theme}
    />
  );
};

export default WarehouseStockReport;
